# Generated by Django 5.1.8 on 2025-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='search_query',
            field=models.CharField(blank=True, help_text="Search query for news API (e.g., 'artificial intelligence' or 'AI development')", max_length=200, null=True),
        ),
    ]
